# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.Lecturer'),
        ),
        migrations.AlterField(
            model_name='results',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Subject'),
        ),
    ]
